"use client";

import React from "react";
import { motion } from "framer-motion";
import { TrendingUp, Scale, Settings } from "lucide-react";

export default function Manifesto() {
    return (
        <section id="manifesto" className="py-24 bg-[var(--color-bg-primary)] border-t border-[var(--color-border-subtle)] relative overflow-hidden">
            {/* Background Accent */}
            <div className="absolute bottom-0 right-0 w-[600px] h-[600px] bg-[var(--color-brand-600)]/5 rounded-full blur-[150px] pointer-events-none" />

            <div className="container mx-auto px-6 lg:px-12 max-w-5xl">
                <div className="mb-16">
                    <h2 className="text-sm font-bold tracking-widest text-[var(--color-brand-500)] uppercase mb-2">
                        The Manifesto
                    </h2>
                    <h3 className="text-4xl md:text-5xl font-extrabold text-[var(--color-text-primary)]">
                        Philosophy & Business ROI
                    </h3>
                </div>

                <div className="space-y-12 lg:space-y-20 relative z-10">

                    <motion.div
                        initial={{ opacity: 0, y: 20 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        viewport={{ once: true }}
                        className="grid grid-cols-1 md:grid-cols-[100px_1fr] gap-6 items-start"
                    >
                        <div className="hidden md:flex flex-col items-center">
                            <div className="w-16 h-16 rounded-full bg-[var(--color-bg-secondary)] border-2 border-[var(--color-brand-500)] flex items-center justify-center text-[var(--color-brand-500)] shadow-[0_0_20px_rgba(16,185,129,0.2)]">
                                <TrendingUp className="w-6 h-6" />
                            </div>
                            <div className="w-0.5 h-full min-h-[100px] bg-gradient-to-b from-[var(--color-brand-500)] to-transparent opacity-50 my-4" />
                        </div>
                        <div className="bg-[var(--color-bg-secondary)] border border-[var(--color-border-subtle)] p-8 lg:p-10 rounded-2xl shadow-xl">
                            <h4 className="text-2xl font-bold text-white mb-4">"Vibe Coding" vs "Brute Force"</h4>
                            <p className="text-lg text-[var(--color-text-secondary)] leading-relaxed mb-6">
                                Brute force coding assumes value is generated by typing fast. It isn't. The real value is in architectural synthesis. By utilizing LLMs to handle syntax generation ("Vibe Coding"), I eliminate mechanical drudgery and treat AI as a direct extension of my thought process.
                            </p>
                            <blockquote className="border-l-4 border-[var(--color-brand-500)] pl-4 text-white font-mono text-sm tracking-wide py-2 bg-[var(--color-bg-primary)] rounded-r flex items-center gap-3">
                                <span>Result:</span> <span className="text-[var(--color-brand-500)]">Faster time-to-market without sacrificing code integrity.</span>
                            </blockquote>
                        </div>
                    </motion.div>

                    <motion.div
                        initial={{ opacity: 0, y: 20 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        viewport={{ once: true }}
                        className="grid grid-cols-1 md:grid-cols-[100px_1fr] gap-6 items-start"
                    >
                        <div className="hidden md:flex flex-col items-center mt-[-40px]">
                            <div className="w-0.5 h-16 bg-gradient-to-t from-[var(--color-border-subtle)] to-transparent opacity-50 mb-4" />
                            <div className="w-16 h-16 rounded-full bg-[var(--color-bg-secondary)] border-2 border-orange-500 flex items-center justify-center text-orange-400 shadow-[0_0_20px_rgba(249,115,22,0.1)]">
                                <Settings className="w-6 h-6" />
                            </div>
                            <div className="w-0.5 h-full min-h-[100px] bg-gradient-to-b from-orange-500 to-transparent opacity-50 my-4" />
                        </div>
                        <div className="bg-[var(--color-bg-secondary)] border border-orange-500/30 p-8 lg:p-10 rounded-2xl shadow-xl">
                            <h4 className="text-2xl font-bold text-orange-400 mb-4">System Design & Technical Debt</h4>
                            <p className="text-lg text-[var(--color-text-secondary)] leading-relaxed">
                                A beautifully styled React component is useless if the database schema introduces a massive N+1 connection bottleneck. I architect with <strong className="text-white">End-to-End Type Safety</strong> and robust, decoupling mental models (like Queues and Edge Caching) to ensure that the infrastructure scales gracefully on day 100, not just day 1. Technical debt is a conscious loan, not an accidental byproduct.
                            </p>
                        </div>
                    </motion.div>

                    <motion.div
                        initial={{ opacity: 0, y: 20 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        viewport={{ once: true }}
                        className="grid grid-cols-1 md:grid-cols-[100px_1fr] gap-6 items-start"
                    >
                        <div className="hidden md:flex flex-col items-center mt-[-40px]">
                            <div className="w-0.5 h-16 bg-gradient-to-t from-[var(--color-border-subtle)] to-transparent opacity-50 mb-4" />
                            <div className="w-16 h-16 rounded-full bg-black border-2 border-blue-500 flex items-center justify-center text-blue-400 shadow-[0_0_40px_rgba(59,130,246,0.3)]">
                                <Scale className="w-6 h-6" />
                            </div>
                        </div>
                        <div className="bg-[linear-gradient(to_right,var(--color-bg-secondary),rgba(59,130,246,0.05))] border border-blue-500/50 p-8 lg:p-10 rounded-2xl shadow-2xl">
                            <h4 className="text-2xl font-bold text-blue-400 mb-4">The Business Shark</h4>
                            <p className="text-lg text-white leading-relaxed mb-6">
                                Technology serves the business; the business does not serve technology. I speak <span className="font-mono text-blue-300">ROI, CAC, and Operational Scaffolding</span> as fluently as I speak TypeScript.
                            </p>
                            <p className="text-[var(--color-text-muted)]">
                                My job isn't to write arbitrary code. It is to build systems that automate overhead, secure endpoints natively, and translate directly into explosive scalability and reduced cloud spend.
                            </p>
                        </div>
                    </motion.div>

                </div>
            </div>
        </section>
    );
}
